parameters:
    # locale type select either long (de_DE) or short (de)
    locale_type:            long

    # Regular Expression to find a locale pattern like 'de_DE' within a string (url)
    regex_locale_long:      |\/(?P<locale>[a-z]{2}_[A-Z]{2})\/|
    regex_locale_short:     |\/(?P<locale>[a-z]{2})\/|

    # Cookie name for user locale
    cookie_name:  tl

services:
    twi.locale.listener:
        class: TWI\MultiDomainLocaleBundle\EventListener\LocaleListener
        arguments:
            - @twi.locale.manager
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    twi.locale.manager:
        class: TWI\MultiDomainLocaleBundle\Service\LocaleManager
        arguments:
            - %localesByCountry%
            - %include_paths%
            - %locale_type%
            - %regex_locale_long%
            - %regex_locale_short%
            - %cookie_name%

    twi.twig.locale:
        class: TWI\MultiDomainLocaleBundle\Service\TwigLocaleManager
        arguments:
            - @service_container
            - @twi.locale.manager
            - %locales_config%
