parameters:

    # all allowed locales, new locales MUST be defined here!!!
    locales_allowed: de_DE|en_GB|de_CH|fr_FR

    # specify which locale is allowed in which country by top level domain
    localesByCountry:
        # Switzerland
        ch:
            name: Switzerland
            locales: [de_CH, fr_FR, en_GB]
            default_locale: de_CH
        # Germany
        de:
            name: Germany
            locales: [de_DE, en_GB]
            default_locale: de_DE

        #add more countries here

        # default, is only for dev environments without a valid top level domain
        default:
            name: Germany
            locales: [de_DE, en_GB]
            default_locale: de_DE

    # Config data for locales, important for language dropdown menu
    locales_config:
        de_DE:
            image: de.gif
            label: Deutsch
        de_CH:
            image: de_ch.gif
            label: Deutsch (Schweiz)
        fr_FR:
            image: fr.gif
            label: Français
        en_GB:
            image: en.gif
            label: English

    # Whitelist of routes, where locale validation is activated
    include_paths:
        - /demo

    # Regular Expression to find a locale pattern like 'de_DE' within a string (url)
    regex_locale: |\/(?P<locale>[a-z]{2}_[A-Z]{2})\/|

    # Cookie name for user locale
    cookie_name:  tl

services:
    twi.locale.listener:
        class: TWI\MultiDomainLocaleBundle\EventListener\LocaleListener
        arguments:
            - @twi.locale.manager
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    twi.locale.manager:
        class: TWI\MultiDomainLocaleBundle\Service\LocaleManager
        arguments:
            - %localesByCountry%
            - %include_paths%
            - %regex_locale%
            - %cookie_name%

    twi.twig.locale:
        class: TWI\MultiDomainLocaleBundle\Service\TwigLocaleManager
        arguments:
            - @service_container
            - @twi.locale.manager
            - %locales_config%
